services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile.backend
    restart: always
    
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./trans-frontend:/usr/share/nginx/html:ro

